[book]
title = "Server Sway Dots"
authors = ["LordPipon"]
description = "Docs for the minimal Server Sway Dots Sway configuration"
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/lordpipon/server-swaydots"
edit-url-template = "https://github.com/lordpipon/server-swaydots/edit/main/{path}"
